name: prototype_app_pang
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  #flutter_localizations:
    #sdk: flutter
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_launcher_icons: ^0.7.0
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  flutter_calendar_carousel: ^1.3.15+4
  expandable: ^2.0.0
  #google_maps_flutter: 0.3.0+1
  google_maps_flutter: ^0.5.13
  geocoder: ^0.1.2
  flutter_google_places: ^0.2.2
  #location: ^2.1.0
  location: 2.3.2
  image_picker: ^0.5.0+3
  tip_dialog: ^2.0.0
  async_loader: 0.1.2
  http: ^0.12.0+1
  queries: ^0.1.12

  flutter_progress_hud: ^1.0.1
  charts_flutter: ^0.6.0
  autocomplete_textfield: ^1.6.6
  flutter_typeahead: ^1.6.0

  #Guy
  dio: ^1.0.0     #ใส่ค้นหา
  english_words: ^3.1.3
  datetime_picker_formfield: ^0.1.8
  file_picker: ^1.3.4+1
  path_provider: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon_app.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.jpg
    - assets/images/logo.png
    - assets/images/logo_login.png
    - assets/images/logo_page.png
    - assets/images/bg.png
    - assets/images/bg_main.png
    - assets/images/avatar.jpg
    - assets/images/opacity.png
    - assets/icons/icon_app.png
    - assets/icons/icon_drawer_tab1.png
    - assets/icons/icon_drawer_tab2.png
    - assets/icons/icon_drawer_tab3.png
    - assets/icons/icon_drawer_tab4.png
    - assets/icons/icon_drawer_tab5.png
    - assets/icons/icon_drawer_tab6.png
    - assets/icons/icon_drawer_tab7.png
    - assets/icons/icon_drawer_tab8.png
    - assets/icons/icon_drawer_tab9.png
    - assets/icons/icon_drawer_tab10.png
    - assets/icons/marker.png
    - assets/icons/icon_drawer_tab5_1.png
    - assets/icons/icon_drawer_tab5_2.png
    - assets/icons/icon_drawer_tab5_3.png
    - assets/icons/icon_drawer_tab5_4.png
    - assets/icons/icon_drawer_tab5_6.png
    - assets/icons/icon_drawer_tab5_7.png
    - assets/icons/icon_drawer_tab5_8.png
    - assets/icons/icon_drawer_tab5_9.png

    #zan
    - assets/images/zan/person_1.jpg
    - assets/images/zan/person_2.jpg
    - assets/images/zan/person_3.JPEG

  fonts:
  - family: Kanit
    fonts:
    - asset: assets/fonts/Kanit-Black.ttf
    - asset: assets/fonts/Kanit-BlackItalic.ttf
    - asset: assets/fonts/Kanit-Bold.ttf
    - asset: assets/fonts/Kanit-BoldItalic.ttf
    - asset: assets/fonts/Kanit-Italic.ttf
    - asset: assets/fonts/Kanit-Light.ttf
    - asset: assets/fonts/Kanit-Medium.ttf
    - asset: assets/fonts/Kanit-Regular.ttf
    - asset: assets/fonts/Kanit-Thin.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
